### ISSUE TITLE
trouble with leadtimes in concat_data_repository

### ISSUE THREAD

**Issue by jfburkhart** [statkraft/shyft#373]
I have a simple test to use the `ConcatDataRepository` with a netcdf file constructed following the docstring. There are no lead_times, so my `lead_time` variable simply an array with [1]. During debugging, I get the following error:

```
v_shift_first = int(v.start - lead_times_in_sec[nb_lead_intervals_to_drop + nb_lead_intervals])
RuntimeError: supplied argument not convertible to time
```
coming from: https://github.com/statkraft/shyft/blob/1a69866830733bbe0a0b1d439ce70824a1fe9b7b/shyft/repository/netcdf/concat_data_repository.py#L671

The following output below is from a debug session, showing that the `v.start` of type ` shyft.api._api.time` cannot subtract the `np.float` coming from the masked array, even thought a `float` can be subtracted from `v.start`.

```
v.start
Out[9]: time(877910400)
lead_times_in_sec
Out[10]: 
masked_array(data=[0.0],
             mask=[False],
       fill_value=nan,
            dtype=float32)
v.start
Out[11]: time(877910400)
v.start - 0.0
Out[12]: time(877910400)
```
no problems above, but when we try to index `lead_times_in_sec` we get an error:

```
v.start - lead_times_in_sec[0]
Traceback (most recent call last):
  File "/auto/energymdl2/anaconda3/envs/commod_py3_20180917/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-578bfede827c>", line 1, in <module>
    v.start - lead_times_in_sec[0]
RuntimeError: supplied argument not convertible to time
```

Not sure if this results from changes in #211 we should probably add some more tests for the `concat_data_repo`

**Comment by sigbjorn** [comment]
It's because we not yet support automatic/implicit conversion of  np. types, like np.int, np.float etc.to e.g.int. As per usual, you solve this by int()-ing or float()-ing(sub-second support, the stuff you extract from the numpy. And yes, with a test in place at the moment of changing to us, it would have been no issue now.

**Comment by jfburkhart** [comment]
Ok. @felixmatt  here is a quick fix, but there are many places in the concat_data_repository to apply this.
```
v_shift_first = int(v.start - int(lead_times_in_sec[nb_lead_intervals_to_drop + nb_lead_intervals]) )
```

and a possible test you could put in place:

```
class ConcatDataRepositoryTestCase(unittest.TestCase):
    """
    Simple tests of concat repo
    """

    @property
    def period(self):
        n_days = 5
        t0 = api.YMDhms(2015, 8, 25)
        utc = api.Calendar()  # No offset gives Utc
        step = api.deltahours(24)
        return api.UtcPeriod(utc.time(t0), utc.time(t0) + api.deltahours(n_days * 24))

    def test_get_timeseries(self):
        # Period start
        t0 = api.YMDhms(2015, 8, 24, 0)
        date_str = "{}{:02}{:02}_{:02}".format(t0.year, t0.month, t0.day, t0.hour)
        utc = api.Calendar()  # No offset gives Utc

        f1 = path.join(shyftdata_dir, "repository", "arome_data_repository",
                       f"arome_metcoop_red_default2_5km_{date_str}_diff_time_unit.nc")
        ar1 = ConcatDataRepository(epsg=EPSG, filename=f1)

        input_source_types = ['temperature']

        ts = ar1.get_timeseries(input_source_types, self.period, geo_location_criteria=None)

        self.assertIsInstance(ts, api.TimeSeries)

```

I would also conduct a test with some geolocations for domains outside of Norway. I am working through some issues on this /atm.

**Comment by sigbjorn** [comment]
api.YMDhms() is deprecated, use calendar.time(Y, M, D...) etc. instead,
also use f-strings, like f'{}' instead of old deprecated "".format(...).
(We did some testing in LTM-project, the f-variant is the faster one).

like:
```python
# :
utc=api.Calendar() # keep this handy
# : 
    @property
    def period(self):
        t0 = utc.time(2015, 8, 25)
        return api.UtcPeriod(t0,t0 + api.deltahours(24*5))

```
